repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
        files: ^infrastructure/.*\.tf$
      - id: terraform_docs
        files: ^infrastructure/.*\.tf$
        args:
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true