services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_ARCH: ${IMAGE_ARCH:?error}
    env_file:
      - .env
    volumes:
        - ./frontend:/app/frontend
        - ./infrastructure:/app/infrastructure