INSERT INTO `car_insurance_products`
VALUES ('001',
        'Car Insurance Basic',
        'Liability',
        'Bi-Weekly',
        '| risk level | rate |\n| ---------- | ---- |\n| low        | 1.5  |\n| medium     | 3.0  |\n| high       | 5.0  |',
        499.99,
        599.99,
        'https://example.com/car-insurance/basic',
        'CAD',
        CURRENT_TIMESTAMP),
       ('002',
        'Car Insurance Premium',
        'Comprehensive',
        'Monthly',
        '| risk level | rate |\n| ---------- | ---- |\n| low        | 2.5  |\n| medium     | 4.0  |\n| high       | 6.0  |',
        899.00,
        1099.00,
        'https://example.com/car-insurance/premium',
        'CAD',
        CURRENT_TIMESTAMP);