INSERT INTO `home_insurance_products`
VALUES ('001',
        'Home Insurance Basic',
        'Dwelling',
        'Bi-Anually',
        '| risk level | rate |\n| ---------- | ---- |\n| low        | 1.5  |\n| medium     | 3.0  |\n| high       | 5.0  |',
        799.99,
        999.99,
        'https://example.com/home-insurance/basic',
        'USD',
        CURRENT_TIMESTAMP),
       ('002',
        'Home Insurance Premium',
        'Comprehensive',
        'Monthly',
        '| risk level | rate |\n| ---------- | ---- |\n| low        | 2.5  |\n| medium     | 4.0  |\n| high       | 6.0  |',
        1499.00,
        1999.00,
        'https://example.com/home-insurance/premium',
        'USD',
        CURRENT_TIMESTAMP);